### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Rellim92** [Bespin-AF/a2d2-ios#62]
As Boot

- Opens App
- Splash Screen shows while beginning processes load
- moves to login page one loaded
<img width="467" alt="Screen Shot 2019-04-23 at 11 03 18 AM" src="https://user-images.githubusercontent.com/45945578/56597147-7c479f80-65b7-11e9-84eb-1e160ee09f32.png">
<img width="324" alt="Screen Shot 2019-04-23 at 11 05 05 AM" src="https://user-images.githubusercontent.com/45945578/56597259-b153f200-65b7-11e9-8efa-767611c05053.png">

**Comment by DCrean** [comment]
Added and Merged
