### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Rellim92** [Bespin-AF/a2d2-ios#76]
<img width="623" alt="Screen Shot 2019-05-28 at 2 48 09 PM" src="https://user-images.githubusercontent.com/45945578/58507620-c6441800-8157-11e9-9967-7f03281eb257.png">

As Boot 
Opens app
Clicks on Driver Login
Fills in email
Clicks Password Reset
clicks confirm on pop up
clicks okay on pop up
checks email to get reset link
resets password
logs in

**Comment by joseph-mills** [comment]
Be aware that this issue is identical to the other one that was opened. Closing other issue and keeping this one open

**Comment by joseph-mills** [comment]
I would change "Clicks Password Reset" to "Clicks Forgot Password."

**Comment by Rellim92** [comment]
<img width="422" alt="Screen Shot 2019-06-04 at 10 56 18 AM" src="https://user-images.githubusercontent.com/45945578/58894348-70232780-86b7-11e9-9dcd-19f7ecc5705e.png">

**Comment by Rellim92** [comment]
<img width="510" alt="Screen Shot 2019-06-04 at 2 13 03 PM" src="https://user-images.githubusercontent.com/45945578/58907071-f6009c00-86d2-11e9-826d-6765691c78d3.png">

**Comment by DCrean** [comment]
I would like to see this Issue re-created so that we can do it right from the start.
