### ISSUE TITLE
Filtering Ride Requests

### ISSUE THREAD

**Issue by joseph-mills** [Bespin-AF/a2d2-ios#78]
Add a segmented control to the ride requests screen to allow users to filter requests by Available, In Progress, and Completed. @Rellim92 need to amend screenshot to change from "Complete" to "Completed" for consistency across the application.

**Comment by Rellim92** [comment]
<img width="740" alt="Screen Shot 2019-06-04 at 11 06 03 AM" src="https://user-images.githubusercontent.com/45945578/58895094-ccd31200-86b8-11e9-85d1-8f01bffb44df.png">

**Comment by DCrean** [comment]
For clarification:
TableViews
- Using transparent background and cells?
- Cell formats changing?
- Cell highlighting based on logged in user?
- Would we like to sort rides assigned to the logged in user to the top?

Navigation Bar
-  Black Text?
- Transparent Background?

UI Controls
- Gestures to swipe between segments?

**Comment by Rellim92** [comment]
keep the same formatting for now

**Comment by Rellim92** [comment]
<img width="270" alt="Screen Shot 2019-06-05 at 10 01 12 AM" src="https://user-images.githubusercontent.com/45945578/58967009-f2275500-8778-11e9-837c-cb732354408f.png">

**Comment by Rellim92** [comment]
the segmented controls will switch between the different types

As boot 
open app
login as driver
click segmented controls to move between types of request status (keep the same info format)

for the bottom bar:

As boot 
open app
login as driver
on login will be in Requests section
clicking Schedule will move to the page and make the icon and text change to selected color, first page will switch to white
will repeat changes for profile page

**Comment by DCrean** [comment]
**Please Note:**
The design decision to use a TableView under a Segment Controller as shown above will require a complete re-work the page.

This is forcing us to create a custom UITableView object to make up for _not_ using the TableViewController how Apple Intended.

I estimate this re-work will take a little over a week to get back to it's current amount of functionality

Feel free to come to me with any questions you may have about this.

**Comment by joseph-mills** [comment]
closed issue due to updated requirements
