### ISSUE TITLE
Able to send test data to the production request table. 

### ISSUE THREAD

**Issue by joseph-mills** [Bespin-AF/a2d2-ios#92]
We need to modify our development branches to send test data to the testRequests table instead of Requests. otherwise, we will be crossing streams

**Comment by joseph-mills** [comment]
@DCrean Is this as easy as modifying 

> static let requests = DataSource(.Requests)

to 

> static let requests = DataSource(.TestRequests) 

in DataSourceUtils.swift ?

**Comment by joseph-mills** [comment]
Okay it IS this easy. So let's get this done.

**Comment by paluzzinator** [comment]
Accepted, Completed and Committed the change to DataSourceUtils.swift
Please verify its completion and close the issue.
